//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub status: String,
    pub description: Option<String>,
    pub created_at: DateTime,
    pub due_date: Option<Date>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::task_project::Entity")]
    TaskProject,
}

impl Related<super::task_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskProject.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        super::task_project::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::task_project::Relation::Task.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
